version: '2'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apache2/sites-available/001-default.conf:/etc/apache2/sites-available/001-default.conf
    depends_on:
      - mysql
      - redis
  redis:
    image: redis
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/:/etc/mysql/conf.d/
